### ISSUE TITLE
Wording inconsistency issue

### ISSUE THREAD

**Issue by amccannv** [Sendouc/sendou-ink#11]
On the FA page, notice how the phrase `Filter by ...` is used three times. The first two filters show FA's who fit that criteria, implying `Filter by` includes the criteria and excludes those not matching criteria. Conversely, the `Filter by weapon` dropdown (which is beautiful btw) works the opposite.

Intuitively, one would suspect that this filter would work in the same way as the first two - I did as I was searching for a Bamboo main and thought it was odd that they all disappeared. I'd argue this type of behaviour is more intuitive and useful, since inclusivity is more important when looking for a teammate - you'd need to really hate a weapon to purposefully exclude it.

I'd also argue that the matching feature should be more obvious - if I get a like I should be able to see who it is. Paginating through ~296 FA's can be such a teasing guessing game. The reason it works with dating apps is because you're presented the matches in a gamified format.

And finally, your code quality is very good! I wish my coworkers kept their code this clean. :shipit:

From a fellow software engineer who focuses on UX :) if you'd like to dm to discuss, you can find me at **drew#6949**.

**Comment by LeptoFlare** [comment]
Interesting that `Filter by weapon` is a blacklist rather than a whitelist.
I'm not sure if this is intentional or not.

It's probable that filtering by weapon was *intended* to filter, and not exclude.

**Comment by Sendouc** [comment]
I have an overhaul of the free agents page in the pipeline that will introduce fixes to some of the underlying issues but I will tackle some of the points you brought up before that in a prioritised manner 👍  

Weapon being a blacklist is indeed very confusing and I think it is just some weird bug I introduced along the way somehow. Thanks for bringing it up.

Regarding showing your matches or not showing your matches I think I will end up changing it so that they are shown. My thinking originally was:

1) People will feel more motivated to go through the FA postings vs. if they just are given who liked them they are more tempted to just skip to those posts while ignoring the less (and this will decrease the amount of likes given in theory)

2) You don't have to feel pressure about liking players that you feel might be "above your league" - they will never know unless they like you back.

Are those points enough to justify it being like that? I'm not sure. I need to think about it when I work on the overhaul.

**Comment by amccannv** [comment]
Not much a bug, I think it might have been a misunderstanding on if you wanted to white or blacklist. The relevant line of code here: https://github.com/Sendouc/sendou-ink/blob/4a6b677962c7658b88fcdcd93f5c86eec90d3099/frontend-react/src/components/freeagents/FreeAgentsPage.tsx#L94

Easy fix ^

With regards to matches, I agree on your points - I think it's fine as is.

**Comment by Sendouc** [comment]
Yeah seems like I broke it when I introduced alt skins to the site: https://github.com/Sendouc/sendou-ink/commit/f2f76083805c8b20bcd12a20eb822930e52c2f02#diff-396109f2790ef72a5e73a1b0f6b43eaf

Thanks for the report! Will fix this in the next update

**Comment by LeptoFlare** [comment]
should I make a quick PR? Or have you got this?

**Comment by Sendouc** [comment]
Probably easier for me to do it but thanks anyway! I should improve the instructions to get the project up and running locally since I don't think it's that feasible right now.

**Comment by Sendouc** [comment]
Fixed now in the live version.
